/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { BaseLayout } from "@/components/base-layout";
import { ThemeProvider } from "@/components/theme-provider";
import { PackageManagerProvider } from "@/components/package-manager/package-manager-context";

const jetBrainsMono = JetBrains_Mono({
    variable: "--font-jetbrains-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <link
                    href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&display=swap"
                    rel="stylesheet"
                />
            </head>
            <body
                className={`${jetBrainsMono.className} h-dvh flex flex-col antialiased bg-background overflow-y-auto`}
            >
                <SidebarProvider defaultOpen={false}>
                    <PackageManagerProvider>
                        <BaseLayout>
                            <ThemeProvider
                                attribute="class"
                                defaultTheme="system"
                                enableSystem
                                disableTransitionOnChange
                            >
                                <div className="flex justify-center w-full">
                                    {children}
                                </div>
                            </ThemeProvider>
                        </BaseLayout>
                    </PackageManagerProvider>
                </SidebarProvider>
            </body>
        </html>
    );
}
